module.version.simter-operation: @project.version@
db:
  platform: @db.platform@
  init-mode: @db.init-mode@
  ddl-auto: @db.ddl-auto@
  host: @db.host@
  port: @db.port@
  name: @db.name@
  username: @db.username@
  password: @db.password@
server:
  port: ${port:9014}
  servlet:
    context-path: /
  server-header: @project.artifactId@-@project.version@
spring:
  main:
    banner-mode: 'OFF'
  profiles:
    active: @spring-active-profiles@
  application:
    name: @project.artifactId@-@project.version@
  jpa:
    open-in-view: false
    hibernate.ddl-auto: ${db.ddl-auto:none}  # none | create | create-drop | update | validate
  datasource:
    continue-on-error: false
    sql-script-encoding: UTF-8
    initialization-mode: ${db.init-mode} # embedded|always|never